### PR TITLE
Download URL for zc.buildout 2 bootstrap has changed.

### PR DESCRIPTION
**Pull request by tisto**
BTW: I still get an error when running "git push heroku master":

```
remote:        Clean up Installer files
remote: -----> Read BUILDOUT_CFG from env vars, or use default
remote:        Using default: heroku.cfg
remote: -----> Read BUILDOUT_VERBOSITY from env vars, or use default
remote:        Use default buildout verbosity
remote: -----> Read BOOTSTRAP_PY_URL from env vars, or use default
remote:        Use custom bootstrap.py: http://bootstrap.pypa.io/bootstrap-buildout.py
remote: -----> Bootstrap buildout
remote:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
remote:                                  Dload  Upload   Total   Spent    Left  Speed
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: L
remote:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
remote: python: can't open file 'bootstrap.py': [Errno 2] No such file or directory
remote: 
remote:  !     Push rejected, failed to compile Plone app
remote: 
remote: Verifying deploy...
remote: 
remote: !   Push rejected to radiant-fjord-99541.
remote: 
```

I ran this command before:

> heroku config:add BOOTSTRAP_PY_URL=http://bootstrap.pypa.io/bootstrap-buildout.py

### CODE REVIEW

**Comment by tisto** [comment]
After I fixed the error above I ran into another one: That add-on plan is only available to select users. Fixed by replacing heroku-postgresql:dev with heroku-postgresql:hobby-dev. See http://stackoverflow.com/questions/27395453/getting-issue-to-add-herokuconnect-addon

**Comment by tisto** [comment]
@zupo any chance to fix travis on master?

**Comment by zupo** [comment]
Someone who understands bash better than me needs to rewrite them. They are currently using our company's account for testing and it sends me an email on every build run. 

A lot has changed on Heroku & Travis in the last 18 months so tests needs to be looked at again and most probably rewritten from scratch.

**Comment by zupo** [comment]
People should really use https://github.com/niteoweb/heroku-buildpack-buildout instead. It's much better. I can move it to `plone` repo if that would help adoption.

**Pull request closed without merging**
